In [1]:
import pandas as pd
import requests

In [2]:
products_url = "https://dummyjson.com/products"
users_url = "https://dummyjson.com/users"
carts_url = "https://dummyjson.com/carts"

In [3]:
resl = requests.get(products_url)

In [4]:
print("products status:",resl.status_code)

products status: 200

In [5]:
products_data =  resl.json()['products']
df_products = pd.DataFrame(products_data)

In [6]:
res2 = requests.get(users_url)

In [7]:
print("users status:",res2.status_code)

users status: 200

In [8]:
users_data =  res2.json()['users']
df_users = pd.DataFrame(users_data)

In [9]:
res3 = requests.get(carts_url)

In [10]:
print("carts status:",res3.status_code)

carts status: 200

In [11]:
carts_data = res3.json()['carts']
df_carts = pd.DataFrame(carts_data)

In [12]:
df_products = df_products[['id','title','price','category','rating']]

In [13]:
df_products.rename(columns = {'id':'product_id'},inplace = True)

In [14]:
df_users['full_name']= df_users['firstName']+" "+df_users['lastName']

In [15]:
df_users['city'] = df_users['address'].apply(lambda X: X['city'])

In [16]:
df_users = df_users[['id','full_name','city','gender','age']]

In [17]:
df_users.rename(columns = {'id':'user_id'},inplace = True)

In [18]:
df_carts = df_carts.explode('products')

In [19]:
df_carts['product_id']= df_carts['products'].apply(lambda X:X['id'])
df_carts['quantity']= df_carts['products'].apply(lambda X:X['quantity'])

In [20]:
df_carts.drop(columns = ['products'],inplace =True)

In [21]:
df_carts.rename(columns ={'id':'cart_id','userid':'user_id'},inplace=True)

In [22]:
df_carts = df_carts.merge(df_products,on="product_id",how = 'left')

In [23]:
df_carts['revenue']= df_carts['price']*df_carts['quantity']

In [24]:
df_carts.head()

,cart_id,total,discountedTotal,userId,totalProducts,totalQuantity,product_id,quantity,title,price,category,rating,revenue
0,1,13037.88,11510.81,1,4,12,162,4,NaN,NaN,NaN,NaN,NaN
1,1,13037.88,11510.81,1,4,12,113,3,NaN,NaN,NaN,NaN,NaN
2,1,13037.88,11510.81,1,4,12,122,3,NaN,NaN,NaN,NaN,NaN
3,1,13037.88,11510.81,1,4,12,138,2,NaN,NaN,NaN,NaN,NaN
4,2,139.93,125.70,2,2,7,86,5,NaN,NaN,NaN,NaN,NaN

In [25]:
df_users.head()

   user_id         full_name          city  gender  age
0        1     Emily Johnson       Phoenix  female   29
1        2  Michael Williams       Houston    male   36
2        3      Sophia Brown    Washington  female   43
3        4       James Davis       Seattle    male   46
4        5       Emma Miller  Jacksonville  female   31

In [27]:
print(df_carts.isnull().sum())

cart_id             0
total               0
discountedTotal     0
userId              0
totalProducts       0
totalQuantity       0
product_id          0
quantity            0
title              94
price              94
category           94
rating             94
revenue            94
dtype: int64

In [39]:
df_carts = df_carts.duplicated().sum()

1

In [43]:
 df_carts = df_carts.drop_duplicates()

In [44]:
df_carts.duplicated().sum()

0

In [46]:
df_users.duplicated().sum()

0

In [45]:
df_products.duplicated().sum()

0

In [32]:
!pip install sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\ProgramData\anaconda3\Lib\site-packages (2.0.34)
Requirement already satisfied: pymysql in C:\Users\XYZ\AppData\Roaming\Python\Python312\site-packages (1.1.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (3.0.1)

In [52]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus
password = quote_plus("Enter_Your_Password")
engine  = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/ecommerce")
engine.connect()
print("connected sucesfully")

connected sucesfully

In [53]:
df_products.to_sql("products",engine,if_exists = "replace",index = False)
df_users.to_sql("users",engine,if_exists = "replace",index = False)
df_carts.to_sql("orders",engine,if_exists = "replace",index = False)

113